# Site wide configuration

title:            bjg.io
locale:           en_US
url:              http://bjg.io
#url:              http://lilmama.cloudapp.net:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Brian Gianforcaro
  avatar: bio-photo.jpg
  bio: "Engineer @ Microsoft"
  email: b.gianfo@gmail.com
  disqus-shortname: 
  twitter: realrbman
  facebook: gianforcaro
  reddit: realrbman
  google:
    plus: BrianGianforcaro
    analytics: UA-105771-3
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: bgianfo
  stackoverflow: 3415/brian-gianforcaro
  linkedin: bgianf
  instagram: #bgianfo
  lastfm: realrbman
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  keybase: bjg
  hackernews: bjg
  coinbase: bjg

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "thumbnail.sh"]
