# Site wide configuration

title:            bjg.io
locale:           en_US
#baseurl:          http://bjg.io
baseurl: http://127.0.0.1:4000

# Jekyll configuration

paginate:    5
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-font-awesome-sass

# Plugin configs
#
jekyll-archives:
  enabled: all

font-awesome:
  assets: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

remote_theme: chesterhow/tale
#remote_theme: nielsenramon/chalk
#remote_theme: yous/whiteglass
#remote_theme: heiswayi/textlog

# Site owner
owner:
  name: Brian Gianforcaro
  avatar: bio-photo.jpg
  bio: "Engineer @ Microsoft"
  email: b.gianfo@gmail.com
  disqus-shortname: bjgio
  github: bgianfo
  twitter: bgianf
  facebook: #gianforcaro
  reddit: #realrbman
  google:
    plus: #BrianGianforcaro
    analytics: UA-105771-3
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  stackoverflow: #3415/brian-gianforcaro
  linkedin: bgianf
  instagram: bgianfo
  lastfm: #realrbman
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  keybase: bjg
  hackernews: bjg
  coinbase: #bjg

include: [".htaccess"]
exclude: [ "README.md", "thumbnail.sh", "Guardfile", "Gemfile"]
